### ISSUE TITLE
R CMD check fails

### ISSUE THREAD

**Issue by stitam** [koralgooll/MulEA#6] opened 2022-05-26 19:45 UTC
First I couldn't Check the package because R couldn't knit the vignette (Issue #5). I simply renamed the `vignette` folder to `vignette_nocheck` to ignore it for now. R CMD check still fails, it seems 7 tests are producing errors:

```
1. Error (testHypergeometricTest.R:31:3): ORA : testData out of DB model.
2. Error (testHypergeometricTest.R:47:3): ORA : testData out of pool. 
3. Error (testHypergeometricTest.R:63:3): ORA : matrix 2,2,2,2.
4. Error (testHypergeometricTest.R:80:3): ORA : pool >> var + DBi, matrix 2,2,2,18.
5. Error (testHypergeometricTest.R:96:3): ORA : DBi not include pool, matrix 2,0,2,2.
6. Error (testHypergeometricTest.R:115:3): ORA : DB1 + DB2 => pool, matrix 1,3,2,2 and 2,2,1,3.
7. Error (testHypergeometricTest.R:137:3): ORA : DB1 + DB2 => pool, matrix 2,2,2,0 and 2,2,1,3.
```

The error message is always the same, see below for first error:

```
Error in `.check_ncores(length(names))`: 4 simultaneous processes spawned
Backtrace:
     ▆
  1. ├─testthat::expect_warning(muleaTestRes <- MulEA::runTest(mulea_ora_model)) at testHypergeometricTest.R:31:2
  2. │ └─testthat:::quasi_capture(enquo(object), label, capture_warnings)
  3. │   ├─testthat .capture(...)
  4. │   │ └─base::withCallingHandlers(...)
  5. │   └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
  6. ├─MulEA::runTest(mulea_ora_model)
  7. └─MulEA::runTest(mulea_ora_model)
  8.   └─testObject@test(testObject)
  9.     ├─MulEA::runTest(muleaSetBaseEnrichmentTest)
 10.     └─MulEA::runTest(muleaSetBaseEnrichmentTest)
 11.       └─testObject@test(testObject)
 12.         └─MulEA:::set.based.enrichment.test.wrapper(...)
 13.           └─MulEA:::set.based.enrichment.test(...)
 14.             └─parallel::makeCluster(spec = nthread, type = "PSOCK", outfile = "log1.txt")
 15.               └─parallel::makePSOCKcluster(names = spec, ...)
 16.                 └─parallel:::.check_ncores(length(names))
```

Any ideas what may be causing these errors? These errors come up when I run Build/Check Package. Interestingly, when I run Build/Test Package, everything is fine, all tests pass.

**Comment by koralgooll** [comment] 2022-05-31 17:58
Hi @stitam, this one require longer investigation, as I am not able to reproduce it. :(

**Comment by koralgooll** [comment] 2022-06-22 16:24
It is fixed now. The reason was that CRAN allows only for two threads, our default in calculations is 4 threads. Same problem with vignette generation in R check. 
Please verify fix on your side. :)

**Closed by koralgooll** 2022-06-22 16:24 UTC
